/** Category slug registry (no manifest imports — safe for next.config). */

export const WORK_CATEGORIES = [
  {
    id: "plotter",
    title: "Plotter / Polargraph",
    slugs: ["plotted-heads"],
    journalSlugs: ["polargraph-process-notes"],
    productSlugs: ["postcards"],
  },
  {
    id: "pc-networks",
    title: "PC Networks",
    slugs: ["ai-image-upscaling"],
    journalSlugs: [],
    productSlugs: [],
  },
  {
    id: "photography",
    title: "Photography",
    slugs: [
      "brighton-by-bench",
      "lightworms",
      "india-2016",
      "painting-studio",
      "drawing-studio",
    ],
    journalSlugs: ["archive-editing-2025"],
    productSlugs: ["limited-prints"],
  },
  {
    id: "film",
    title: "Film / Animation",
    slugs: ["frame-animation-series"],
    journalSlugs: [],
    productSlugs: [],
  },
  {
    id: "crypto",
    title: "Crypto / NFT",
    slugs: [],
    journalSlugs: [
      "crypto-art-value-paradigm",
      "the-problem-of-value",
      "crypto-art-research",
    ],
    productSlugs: ["digital-editions"],
  },
  {
    id: "woodworking",
    title: "Woodworking",
    slugs: ["shelving-a-level", "needle-file-handle", "knife-poster"],
    journalSlugs: [],
    productSlugs: [],
  },
  {
    id: "metalworking",
    title: "Metalworking",
    slugs: ["meat-hammer"],
    journalSlugs: [],
    productSlugs: [],
  },
  {
    id: "nursery",
    title: "Plant / Tree Nursery",
    slugs: [],
    journalSlugs: [],
    productSlugs: [],
  },
  {
    id: "philosophy",
    title: "Philosophy / Writings",
    slugs: [
      "design-philosophy",
      "designing-dope",
      "liminal-design",
      "theories-thinking-design",
    ],
    journalSlugs: [
      "nationalism",
      "god-metaphysical-reality",
      "poverty-of-the-input",
      "strata-judgements-of-god",
      "strata-notes",
      "nature-stars-sky",
      "ur-antifascism",
      "firmament-godhead",
      "universities",
      "rhizome-dota-ti9",
      "poems-blink",
      "poems-fractionation",
    ],
    productSlugs: [],
  },
];
